apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-hgpeer1-cli
  namespace: hgpeer1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-hgpeer1-cli
  chart:
    git: https://github.com/balajihg/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: hgpeer1-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: hgpeer1sc
      size: 256Mi
    vault:
      role: vault-role
      address: http://dev1.vaultservice.hyperrnd.com
      authpath: devhgpeer1-net-auth
      adminsecretprefix: fabric7/crypto/peerOrganizations/hgpeer1-net/users/admin
      orderersecretprefix: fabric7/crypto/peerOrganizations/hgpeer1-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: hgpeer1MSP
      tlsstatus: true
      address: peer0.hgpeer1-net.dev1.fabrictest.hyperrnd.com
    orderer:
      address: orderer1.hgrnd-net:7050
