apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hgrnd-hgrnd-steward-2
  annotations:
    fluxcd.io/automated: "false"
  namespace: hgrnd-ns
spec:
  releaseName: hgrnd-hgrnd-steward-2
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/balajihg/blockchain-automation-framework.git
    ref: main
  values:
    metadata:
      name: hgrnd-hgrnd-steward-2
      namespace: hgrnd-ns
    network:
      name: hrnd
    image:
      name: hgrnd
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://dev1.vaultservice.hyperrnd.com
      keyPath: hgrnd.stewards
      identity: hgrnd-steward-2
      auth_path: kubernetes-hgrnd-admin-auth
    account:
      service: hgrnd-admin-vault-auth
      role: rw
