apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hgrnd1-hgrnd-steward-2-vault-auth-role-binding
  namespace: hgrnd1-ns
  labels:
    organization: hgrnd1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: hgrnd1-hgrnd-steward-2-vault-auth
  namespace: hgrnd1-ns
